export * from "./new-post-form/new-post-form.component"
export * from "./order-gym-pass/order-gym-pass.component"
export * from "./password-changer/password-changer.component"
export * from "./post-details/post-details.component"
export * from "./profile-data-editor/profile-data-editor.component"
export * from "./add-training/add-training.component"
export * from "./add-diet/add-diet.component"
export * from "./change-user-password/change-user-password.component"
export * from "./edit-gym-passes/edit-gym-passes.component"
export * from "./edit-permissions/edit-permissions.component"
export * from "./edit-user-data/edit-user-data.component"
export * from "./gym-pass-requests/gym-pass-requests.component"

